import { NextRequest, NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase/server";
import type { User } from "@supabase/supabase-js";

async function getUser(request: NextRequest): Promise<User | null> { const token = request.headers.get("authorization")?.replace(/^Bearer\s+/i, ""); if (!token || !supabaseAdmin) return null; const { data } = await supabaseAdmin.auth.getUser(token); return data.user ?? null; }
function clean(value: unknown) { return String(value ?? "").replace(/<script[\s\S]*?<\/script>/gi, "").replace(/<[^>]*>/g, "").replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g, "").trim().slice(0, 5000); }
function id(value: unknown) { const parsed = Number(value); return Number.isInteger(parsed) ? parsed : null; }
async function notify(recipientId: string, actorId: string, type: string, entityId: string, bookId: number, message: string) { if (!supabaseAdmin || recipientId === actorId) return; await supabaseAdmin.from("notifications").insert({ recipient_id: recipientId, actor_id: actorId, type, entity_id: entityId, book_id: bookId, message }); }

export async function GET(request: NextRequest) {
  if (!supabaseAdmin) return NextResponse.json({ error: "Supabase unavailable" }, { status: 500 });
  const bookId = id(request.nextUrl.searchParams.get("bookId")); if (bookId === null) return NextResponse.json({ error: "bookId required" }, { status: 400 });
  const page = Math.max(0, Number(request.nextUrl.searchParams.get("page") ?? 0)); const sort = request.nextUrl.searchParams.get("sort") ?? "newest"; const size = 10;
  const order = sort === "oldest" ? ["created_at", true] : sort === "liked" ? ["likes_count", false] : ["created_at", false];
  const { data: comments, count, error } = await supabaseAdmin.from("comments").select("id,user_id,book_id,body,likes_count,status,created_at,updated_at", { count: "exact" }).eq("book_id", bookId).eq("status", "published").order(order[0] as string, { ascending: order[1] as boolean }).range(page * size, page * size + size - 1);
  if (error) return NextResponse.json({ error: "Unable to load discussion" }, { status: 500 }); const rows = comments ?? []; const commentIds = rows.map((row) => row.id); const user = await getUser(request);
  const [replies, profiles] = await Promise.all([supabaseAdmin.from("comment_replies").select("id,comment_id,user_id,body,likes_count,created_at,updated_at").in("comment_id", commentIds).eq("status", "published").order("created_at"), supabaseAdmin.from("profiles").select("id,full_name,avatar_url").in("id", [...new Set(rows.map((row) => row.user_id))])]);
  const replyIds = (replies.data ?? []).map((row) => row.id);
  const likes = user ? await supabaseAdmin.from("comment_likes").select("comment_id,reply_id").eq("user_id", user.id).or(`comment_id.in.(${commentIds.join(",")}),reply_id.in.(${replyIds.join(",")})`) : { data: [] };
  const profileMap = new Map((profiles.data ?? []).map((profile) => [profile.id, profile])); const likedComments = new Set((likes.data ?? []).filter((like) => like.comment_id).map((like) => like.comment_id));
  const result = rows.map((comment) => ({ ...comment, profile: profileMap.get(comment.user_id) ?? null, liked: likedComments.has(comment.id), replies: (replies.data ?? []).filter((reply) => reply.comment_id === comment.id).map((reply) => ({ ...reply, liked: (likes.data ?? []).some((like) => like.reply_id === reply.id) })) }));
  return NextResponse.json({ comments: result, count: count ?? 0 });
}

export async function POST(request: NextRequest) {
  if (!supabaseAdmin) return NextResponse.json({ error: "Supabase unavailable" }, { status: 500 }); const user = await getUser(request); if (!user) return NextResponse.json({ error: "Authentication required" }, { status: 401 });
  const body = await request.json() as Record<string, unknown>; const action = body.action; const bookId = id(body.bookId); const commentId = String(body.commentId ?? ""); const replyId = String(body.replyId ?? "");
  if (action === "create" || action === "update") { const text = clean(body.body); if (!text || bookId === null) return NextResponse.json({ error: "Comment and book are required" }, { status: 400 }); const payload = { body: text, updated_at: new Date().toISOString() }; const result = action === "create" ? await supabaseAdmin.from("comments").insert({ ...payload, book_id: bookId, user_id: user.id }).select().single() : await supabaseAdmin.from("comments").update(payload).eq("id", commentId).eq("user_id", user.id).select().single(); if (result.error) return NextResponse.json({ error: "Unable to save comment" }, { status: 400 }); return NextResponse.json({ comment: result.data }); }
  if (action === "reply") { const text = clean(body.body); if (!text || !commentId || bookId === null) return NextResponse.json({ error: "Reply and parent comment are required" }, { status: 400 }); const parent = await supabaseAdmin.from("comments").select("user_id").eq("id", commentId).single(); const result = await supabaseAdmin.from("comment_replies").insert({ comment_id: commentId, user_id: user.id, body: text }).select().single(); if (result.error) return NextResponse.json({ error: "Unable to save reply" }, { status: 400 }); if (parent.data) await notify(parent.data.user_id, user.id, "comment_reply", result.data.id, bookId, "Someone replied to your comment."); return NextResponse.json({ reply: result.data }); }
  if (action === "delete") { const table = replyId ? "comment_replies" : "comments"; const result = await supabaseAdmin.from(table).delete().eq("id", replyId || commentId).eq("user_id", user.id); if (result.error) return NextResponse.json({ error: "Unable to delete comment" }, { status: 400 }); return NextResponse.json({ ok: true }); }
  if (action === "like") { const targetReply = Boolean(replyId); const query = supabaseAdmin.from("comment_likes"); const liked = Boolean(body.liked); const result = liked ? await query.insert({ user_id: user.id, ...(targetReply ? { reply_id: replyId } : { comment_id: commentId }) }) : await query.delete().eq("user_id", user.id).eq(targetReply ? "reply_id" : "comment_id", targetReply ? replyId : commentId); if (result.error && result.error.code !== "23505") return NextResponse.json({ error: "Unable to update like" }, { status: 400 }); const { count } = await supabaseAdmin.from("comment_likes").select("id", { count: "exact", head: true }).eq(targetReply ? "reply_id" : "comment_id", targetReply ? replyId : commentId); return NextResponse.json({ liked, likes: count ?? 0 }); }
  if (action === "report") { const reason = String(body.reason ?? "other"); const result = await supabaseAdmin.from("comment_reports").insert({ user_id: user.id, ...(replyId ? { reply_id: replyId } : { comment_id: commentId }), reason, details: clean(body.details).slice(0, 1000) }); if (result.error) return NextResponse.json({ error: "Unable to submit report" }, { status: 400 }); const target = await supabaseAdmin.from(replyId ? "comment_replies" : "comments").select("user_id").eq("id", replyId || commentId).single(); if (target.data && bookId !== null) await notify(target.data.user_id, user.id, "comment_reported", replyId || commentId, bookId, "Your comment was reported for review."); return NextResponse.json({ ok: true }); }
  return NextResponse.json({ error: "Unknown action" }, { status: 400 });
}
