import { Search, Flag } from "lucide-react";
import { requireAdmin } from "@/lib/supabase/admin";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { ReviewActions } from "./ReviewActions";

export default async function AdminReviewsPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; page?: string }> }) {
  await requireAdmin();
  const params = await searchParams; const page = Math.max(0, Number(params.page ?? 0)); const size = 20; const supabase = await createSupabaseServerClient();
  let query = supabase.from("reviews").select("id,book_id,user_id,rating,title,body,status,likes_count,created_at", { count: "exact" }).order("created_at", { ascending: false }).range(page * size, page * size + size - 1);
  if (params.status && params.status !== "all") query = query.eq("status", params.status);
  if (params.q) query = query.or(`title.ilike.%${params.q}%,body.ilike.%${params.q}%`);
  const { data: reviews, count } = await query;
  const { data: reports } = await supabase.from("review_reports").select("id,review_id,reason,status,created_at").eq("status", "open").order("created_at", { ascending: false }).limit(20);
  return <div className="space-y-6 p-5 sm:p-7"><div><h1 className="text-xl font-bold text-slate-900">Reviews & reports</h1><p className="mt-1 text-sm text-slate-500">Moderate reader feedback and investigate reports.</p></div>{reports?.length ? <div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="flex items-center gap-2 text-sm font-semibold text-amber-800"><Flag className="h-4 w-4" /> {reports.length} open report{reports.length === 1 ? "" : "s"}</p><div className="mt-3 space-y-2 text-xs text-amber-800">{reports.map((report) => <p key={report.id}>Review {report.review_id}: {report.reason}</p>)}</div></div> : null}<form className="flex flex-wrap gap-3"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input name="q" defaultValue={params.q} placeholder="Search reviews" className="h-9 rounded-lg border border-slate-200 bg-white pl-9 pr-3 text-sm" /></div><select name="status" defaultValue={params.status ?? "all"} className="h-9 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="all">All statuses</option><option value="published">Published</option><option value="reported">Reported</option><option value="hidden">Hidden</option></select><button className="h-9 rounded-lg bg-slate-900 px-4 text-sm font-medium text-white">Filter</button></form><div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Review</th><th className="px-4 py-3">Book</th><th className="px-4 py-3">Rating</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Date</th><th className="px-4 py-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{reviews?.map((review) => <tr key={review.id}><td className="max-w-md px-4 py-3"><p className="font-medium text-slate-900">{review.title || "Untitled review"}</p><p className="truncate text-xs text-slate-500">{review.body}</p></td><td className="px-4 py-3 text-slate-500">{review.book_id}</td><td className="px-4 py-3">{review.rating}/5 · {review.likes_count}</td><td className="px-4 py-3 capitalize">{review.status}</td><td className="px-4 py-3 text-xs text-slate-500">{new Date(review.created_at).toLocaleDateString()}</td><td className="px-4 py-3"><ReviewActions id={review.id} status={review.status} /></td></tr>)}</tbody></table>{!reviews?.length && <p className="p-10 text-center text-sm text-slate-500">No reviews found.</p>}</div><p className="text-xs text-slate-500">{count ?? 0} total reviews</p></div>;
}
